module.exports = `/**
 * Express session migration template generated by jwt-session-converter.
 * Replace MemoryStore with Redis or a durable store in production.
 */
const express = require("express");
const session = require("express-session");
const csrf = require("csurf");

const app = express();

app.use(
  session({
    name: "sid",
    secret: process.env.SESSION_SECRET,
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "lax",
      maxAge: 1000 * 60 * 60 * 12
    }
  })
);

app.use(csrf());

app.post("/auth/login", (req, res) => {
  req.session.userId = "replace-with-real-user-id";
  res.json({ ok: true });
});

app.post("/auth/logout", (req, res) => {
  req.session.destroy(() => {
    res.clearCookie("sid");
    res.status(204).end();
  });
});

app.get("/api/me", (req, res) => {
  if (!req.session.userId) {
    return res.status(401).json({ error: "unauthorized" });
  }
  res.json({ userId: req.session.userId });
});
`;
