module.exports = `/**
 * Next.js App Router session migration template generated by jwt-session-converter.
 * Add durable session storage (Redis/Postgres) before production rollout.
 */
import crypto from "node:crypto";
import { cookies } from "next/headers";

const SESSION_COOKIE = "sid";

function sign(value) {
  const sig = crypto.createHmac("sha256", process.env.SESSION_SECRET).update(value).digest("hex");
  return value + "." + sig;
}

export async function issueSession(userId) {
  const token = sign(crypto.randomBytes(24).toString("hex"));
  const cookieStore = await cookies();
  cookieStore.set({
    name: SESSION_COOKIE,
    value: token,
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    maxAge: 60 * 60 * 12
  });

  // Persist token->user mapping in your server session store.
  return token;
}

export async function clearSession() {
  const cookieStore = await cookies();
  cookieStore.set({
    name: SESSION_COOKIE,
    value: "",
    path: "/",
    maxAge: 0
  });
}
`;
