#!/usr/bin/env node

const fs = require("fs-extra");
const path = require("node:path");
const { parse } = require("@babel/parser");
const ts = require("typescript");
const { globSync } = require("glob");
const { Command } = require("commander");
const inquirer = require("inquirer");
const chalk = require("chalk");

const SOURCE_GLOBS = ["**/*.{js,jsx,ts,tsx,mjs,cjs}"];
const IGNORE_GLOBS = ["**/node_modules/**", "**/.next/**", "**/dist/**", "**/build/**", "**/coverage/**"];

const EXPRESS_TEMPLATE = `/**
 * Express session migration template generated by jwt-session-converter.
 * Replace MemoryStore with Redis or a durable store in production.
 */
const express = require("express");
const session = require("express-session");
const csrf = require("csurf");

const app = express();

app.use(
  session({
    name: "sid",
    secret: process.env.SESSION_SECRET,
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      secure: process.env.NODE_ENV === "production",
      sameSite: "lax",
      maxAge: 1000 * 60 * 60 * 12
    }
  })
);

app.use(csrf());

app.post("/auth/login", (req, res) => {
  const userId = req.body?.userId || req.body?.email || "unknown-user";
  req.session.userId = userId;
  res.json({ ok: true, userId });
});

app.post("/auth/logout", (req, res) => {
  req.session.destroy(() => {
    res.clearCookie("sid");
    res.status(204).end();
  });
});

app.get("/api/me", (req, res) => {
  if (!req.session.userId) {
    return res.status(401).json({ error: "unauthorized" });
  }
  res.json({ userId: req.session.userId });
});
`;

const NEXTJS_TEMPLATE = `/**
 * Next.js App Router session migration template generated by jwt-session-converter.
 * Add durable session storage (Redis/Postgres) before production rollout.
 */
import crypto from "node:crypto";
import { cookies } from "next/headers";

const SESSION_COOKIE = "sid";

function sign(value) {
  const sig = crypto.createHmac("sha256", process.env.SESSION_SECRET).update(value).digest("hex");
  return value + "." + sig;
}

export async function issueSession(userId) {
  const token = sign(crypto.randomBytes(24).toString("hex"));
  const cookieStore = await cookies();
  cookieStore.set({
    name: SESSION_COOKIE,
    value: token,
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    maxAge: 60 * 60 * 12
  });

  // Persist token->user mapping in your server session store.
  return { token, userId };
}

export async function clearSession() {
  const cookieStore = await cookies();
  cookieStore.set({
    name: SESSION_COOKIE,
    value: "",
    path: "/",
    maxAge: 0
  });
}
`;

function buildFinding(file, line, code, type, risk, recommendation) {
  return { file, line, code, type, risk, recommendation };
}

function safeParseBabel(code) {
  try {
    return parse(code, {
      sourceType: "unambiguous",
      plugins: ["typescript", "jsx", "decorators-legacy"]
    });
  } catch {
    return null;
  }
}

function detectWithAst(code, relativePath) {
  const findings = [];
  const ast = safeParseBabel(code);
  if (!ast) return findings;

  const lines = code.split("\n");

  function visit(node) {
    if (!node || typeof node !== "object") return;

    if (node.type === "MemberExpression" && !node.computed) {
      if (
        node.object &&
        node.object.type === "Identifier" &&
        node.object.name === "localStorage" &&
        node.property &&
        node.property.type === "Identifier" &&
        ["setItem", "getItem"].includes(node.property.name)
      ) {
        const line = node.loc?.start.line || 1;
        findings.push(
          buildFinding(
            relativePath,
            line,
            lines[line - 1]?.trim() || "localStorage token access",
            "browser-token-storage",
            "high",
            "Replace localStorage token reads/writes with HttpOnly session cookies and server session lookups."
          )
        );
      }
    }

    if (node.type === "StringLiteral" || node.type === "Literal") {
      const value = typeof node.value === "string" ? node.value.toLowerCase() : "";
      if (value.includes("authorization") || value.includes("bearer")) {
        const line = node.loc?.start.line || 1;
        findings.push(
          buildFinding(
            relativePath,
            line,
            lines[line - 1]?.trim() || "Authorization header usage",
            "bearer-header-coupling",
            "medium",
            "Move identity to server session middleware and reduce bearer token fan-out."
          )
        );
      }
    }

    if (node.type === "Identifier" && ["jsonwebtoken", "jwt", "sign", "verify"].includes(node.name)) {
      const line = node.loc?.start.line || 1;
      findings.push(
        buildFinding(
          relativePath,
          line,
          lines[line - 1]?.trim() || "JWT library identifier",
          "jwt-library-reference",
          "medium",
          "Audit this usage and replace auth-critical paths with session storage and rotation."
        )
      );
    }

    for (const key of Object.keys(node)) {
      const value = node[key];
      if (Array.isArray(value)) {
        value.forEach(visit);
      } else if (value && typeof value === "object") {
        visit(value);
      }
    }
  }

  visit(ast.program);
  return findings;
}

function detectWithTypeScriptScanner(code, relativePath) {
  const findings = [];
  const sourceFile = ts.createSourceFile(relativePath, code, ts.ScriptTarget.Latest, true);
  const lines = sourceFile.text.split("\n");

  function scan(node) {
    if (ts.isStringLiteral(node)) {
      const value = node.text.toLowerCase();
      if (value.includes("jwt") || value.includes("token")) {
        const lineAndChar = sourceFile.getLineAndCharacterOfPosition(node.getStart());
        const line = lineAndChar.line + 1;
        findings.push(
          buildFinding(
            relativePath,
            line,
            lines[line - 1]?.trim() || "JWT-related string literal",
            "token-string-literal",
            "low",
            "Confirm this string is not part of insecure client-side token persistence."
          )
        );
      }
    }

    ts.forEachChild(node, scan);
  }

  scan(sourceFile);
  return findings;
}

async function detectJwtPatterns(projectDir) {
  const absoluteProjectDir = path.resolve(projectDir);
  const files = SOURCE_GLOBS.flatMap((pattern) =>
    globSync(pattern, {
      cwd: absoluteProjectDir,
      absolute: true,
      ignore: IGNORE_GLOBS,
      nodir: true
    })
  );

  const deduped = [...new Set(files)];
  const findings = [];

  for (const file of deduped) {
    const content = await fs.readFile(file, "utf8");
    const relativePath = path.relative(absoluteProjectDir, file);

    const astFindings = detectWithAst(content, relativePath);
    const tsFindings = detectWithTypeScriptScanner(content, relativePath);

    for (const finding of [...astFindings, ...tsFindings]) {
      findings.push(finding);
    }
  }

  const unique = [];
  const seen = new Set();
  for (const finding of findings) {
    const key = `${finding.file}:${finding.line}:${finding.type}`;
    if (!seen.has(key)) {
      seen.add(key);
      unique.push(finding);
    }
  }

  return {
    filesScanned: deduped.length,
    findings: unique,
    summary: {
      high: unique.filter((item) => item.risk === "high").length,
      medium: unique.filter((item) => item.risk === "medium").length,
      low: unique.filter((item) => item.risk === "low").length
    }
  };
}

function buildRiskChecklist(findings) {
  const browserStorageFindings = findings.filter((item) => item.type === "browser-token-storage");
  const bearerCouplingFindings = findings.filter((item) => item.type === "bearer-header-coupling");

  const checklist = [
    "Rotate all existing JWT signing keys after migration cutover.",
    "Set session cookies to HttpOnly + Secure + SameSite=Lax/Strict.",
    "Enable CSRF protection for all state-changing form and API routes.",
    "Introduce forced logout endpoint to invalidate server session state."
  ];

  if (browserStorageFindings.length > 0) {
    checklist.push("Remove all client-side token storage reads/writes discovered by analyzer before release.");
  }

  if (bearerCouplingFindings.length > 0) {
    checklist.push("Refactor Authorization-header-only guards to read user identity from the session store.");
  }

  return checklist;
}

async function generateMigrationFiles(outputDir, analysis) {
  const out = path.resolve(outputDir);
  await fs.mkdirp(out);

  const reportPath = path.join(out, "jwt-analysis-report.json");
  await fs.writeJson(reportPath, analysis, { spaces: 2 });

  const migrationPath = path.join(out, "migration-plan.md");
  const checklist = buildRiskChecklist(analysis.findings);
  const byRisk = {
    high: analysis.findings.filter((item) => item.risk === "high"),
    medium: analysis.findings.filter((item) => item.risk === "medium"),
    low: analysis.findings.filter((item) => item.risk === "low")
  };

  const migrationMarkdown = `# JWT to Session Migration Plan

## Scan Summary
- Files scanned: ${analysis.filesScanned}
- High risk findings: ${analysis.summary.high}
- Medium risk findings: ${analysis.summary.medium}
- Low risk findings: ${analysis.summary.low}

## Priority Findings
${["high", "medium", "low"]
  .map((risk) => {
    const entries = byRisk[risk];
    if (entries.length === 0) return `### ${risk.toUpperCase()}\n- None`;
    return `### ${risk.toUpperCase()}\n${entries
      .slice(0, 15)
      .map((item) => `- ${item.file}:${item.line} (${item.type}) -> ${item.recommendation}`)
      .join("\\n")}`;
  })
  .join("\\n\\n")}

## Recommended Rollout Sequence
1. Add session middleware, cookie hardening, and CSRF protections server-side.
2. Add transition adapters so existing JWT-authenticated traffic remains functional temporarily.
3. Remove localStorage token writes and frontend bearer token dispatch.
4. Cut over login/logout flows to session issuance and invalidation.
5. Rotate JWT keys, remove fallback middleware, and rerun analyzer.

## Security Checklist
${checklist.map((item) => `- [ ] ${item}`).join("\\n")}
`;

  await fs.writeFile(migrationPath, migrationMarkdown, "utf8");

  const templatesDir = path.join(out, "generated-templates");
  await fs.mkdirp(templatesDir);
  await fs.writeFile(path.join(templatesDir, "express-session-migration.js"), EXPRESS_TEMPLATE, "utf8");
  await fs.writeFile(path.join(templatesDir, "nextjs-session-migration.ts"), NEXTJS_TEMPLATE, "utf8");

  return {
    reportPath,
    migrationPath,
    templatesDir
  };
}

const program = new Command();

program
  .name("jwt-session-converter")
  .description("Convert JWT auth implementations to secure server-side sessions")
  .option("-p, --project <dir>", "Path to project to analyze", process.cwd())
  .option("-o, --out <dir>", "Output directory for generated migration files", "./jwt-session-migration")
  .option("--yes", "Skip interactive confirmation", false)
  .action(async (options) => {
    const projectDir = path.resolve(options.project);
    const outputDir = path.resolve(options.out);

    console.log(chalk.cyan("\nJWT Session Converter"));
    console.log(chalk.gray(`Project: ${projectDir}`));
    console.log(chalk.gray(`Output: ${outputDir}\n`));

    const exists = await fs.pathExists(projectDir);
    if (!exists) {
      console.error(chalk.red(`Project path does not exist: ${projectDir}`));
      process.exit(1);
    }

    if (!options.yes) {
      const response = await inquirer.prompt([
        {
          type: "confirm",
          name: "proceed",
          message: "Run JWT usage analysis and generate session migration files?",
          default: true
        }
      ]);
      if (!response.proceed) {
        console.log(chalk.yellow("Cancelled."));
        process.exit(0);
      }
    }

    try {
      const analysis = await detectJwtPatterns(projectDir);

      console.log(chalk.green(`Scanned ${analysis.filesScanned} files.`));
      console.log(
        chalk.yellow(`Findings: high=${analysis.summary.high}, medium=${analysis.summary.medium}, low=${analysis.summary.low}`)
      );

      const generated = await generateMigrationFiles(outputDir, analysis);

      console.log(chalk.green("\nGenerated migration artifacts:"));
      console.log(chalk.white(`- ${generated.reportPath}`));
      console.log(chalk.white(`- ${generated.migrationPath}`));
      console.log(chalk.white(`- ${generated.templatesDir}`));
      console.log(chalk.cyan("\nNext step: apply templates into your auth stack and rerun analyzer after each milestone."));
    } catch (error) {
      console.error(chalk.red("CLI execution failed."));
      console.error(error instanceof Error ? error.stack : error);
      process.exit(1);
    }
  });

program.parseAsync(process.argv);
